package org.kurt.utils.bitstamp

val validSymbols = hashSetOf(
    "1incheur", "1inchusd", "aavebtc", "aaveeur", "aaveusd", "adabtc", "adaeur", "adausd",
    "algoeur", "algousd", "ampeur", "ampusd", "apeeur", "apeusd", "arbeur", "arbusd",
    "audioeur", "audiousd", "avaxeur", "avaxusd", "axseur", "axsusd", "bateur", "batusd",
    "bchbtc", "bcheur", "bchusd", "blureur", "blurusd", "bomeeur", "bomeusd", "bonkeur",
    "bonkusd", "btceur", "btcgbp", "btcrlusd", "btcusd", "btcusd-perp", "btcusdc", "btcusdt",
    "chzeur", "chzusd", "compeur", "compusd", "coreumeur", "coreumusd", "crveur", "crvusd",
    "cspreur", "csprusd", "ctsieur", "ctsiusd", "ctxeur", "ctxusd", "cxteur", "cxtusd",
    "daiusd", "dogeeur", "dogeusd", "doteur", "dotusd", "egldeur", "egldusd", "enjeur",
    "enjusd", "enseur", "ensusd", "eth2eth", "ethbtc", "etheur", "ethgbp", "ethrlusd",
    "ethusd", "ethusd-perp", "ethusdc", "ethusdt", "eurcveur", "eurcvusdt", "euroceur",
    "eurocusdc", "eurusd", "fartcoineur", "fartcoinusd", "feteur", "fetusd", "flokieur",
    "flokiusd", "flreur", "flrusd", "ftmeur", "ftmusd", "galaeur", "galausd", "gbpusd",
    "grteur", "grtusd", "gyenusd", "hbareur", "hbarusd", "icpeur", "icpusd", "imxeur",
    "imxusd", "injeur", "injusd", "jupeur", "jupusd", "knceur", "kncusd", "ldoeur",
    "ldousd", "linkbtc", "linkeur", "linkgbp", "linkusd", "lmwreur", "lmwrusd", "lrceur",
    "lrcusd", "ltcbtc", "ltceur", "ltcusd", "manaeur", "manausd", "maticeur", "maticusd",
    "melaniaeur", "melaniausd", "meweur", "mewusd", "mkreur", "mkrusd", "mogeur", "mogusd",
    "neareur", "nearusd", "ondoeur", "ondousd", "opeur", "opusd", "pengueur", "penguusd",
    "pepeeur", "pepeusd", "perpeur", "perpusd", "pnuteur", "pnutusd", "popcateur",
    "popcatusd", "pytheur", "pythusd", "pyusdeur", "pyusdusd", "rlusdeur", "rlusdusd",
    "rlusdusdt", "rndreur", "rndrusd", "sandeur", "sandusd", "seieur", "seiusd", "sgbeur",
    "sgbusd", "shibeur", "shibusd", "skleur", "sklusd", "smteur", "smtusd", "snxeur",
    "snxusd", "soleur", "solusd", "storjeur", "storjusd", "strkeur", "strkusd", "suieur",
    "suiusd", "sushieur", "sushiusd", "syrupeur", "syrupusd", "traceur", "tracusd",
    "trufeur", "trufusd", "trumpeur", "trumpusd", "umaeur", "umausd", "unibtc", "unieur",
    "uniusd", "usdceur", "usdcusd", "usdcusdt", "usdteur", "usdtusd", "vchfeur", "vchfusd",
    "veureur", "veurusd", "wbtcbtc", "wecaneur", "wecanusd", "weneur", "wenusd", "wifeur",
    "wifusd", "wooeur", "woousd", "xchngeur", "xchngusd", "xdceur", "xdcusd", "xlmbtc",
    "xlmeur", "xlmgbp", "xlmusd", "xrpbtc", "xrpeur", "xrpgbp", "xrprlusd", "xrpusd",
    "xrpusdt", "xsgdusd", "xsgdusdt", "yfieur", "yfiusd", "zetaeur", "zetausd", "zrxeur",
    "zrxusd", "zusdusd"
)